version: '3.8'

services:
  taskmanagement-api:
    build:
      context: ./TaskManagementAPI
      dockerfile: Dockerfile
    ports:
      - "5000:8080"
      - "5001:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=TaskManagementDB;User Id=sa;Password=YourStrong@Passw0rd;TrustServerCertificate=true;
    depends_on:
      - sqlserver
    networks:
      - taskmanagement-network

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong@Passw0rd
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    networks:
      - taskmanagement-network

volumes:
  sqlserver_data:

networks:
  taskmanagement-network:
    driver: bridge
